## Other key bindings
# Mouse buttons and wheel
MBTN_LEFT           cycle pause
MBTN_LEFT           cycle pause                         #event: click
MBTN_LEFT           cycle fullscreen                    #event: double_click
MBTN_LEFT_DBL       ignore
MBTN_RIGHT          script-binding uosc/menu
WHEEL_DOWN          no-osd add volume -2; show-text "Volume: ${volume}%"
WHEEL_UP            no-osd add volume +2; show-text "Volume: ${volume}%"
# Long-press right for seek (inputevent.lua)
# Right               seek 5                              #event: click
# Right               no-osd set speed 5; set pause no    #event: press
# Right               ignore                              #event: release
# Via evafast.lua script
Right               seek 5                                          #event: click
Right               set pause no; script-binding evafast/speedup    #event: press
Right               script-binding evafast/slowdown                 #event: release
Space               cycle pause
p                   cycle pause
f                   cycle fullscreen
Esc                 set fullscreen no
o                   show-progress
P                   show-progress
i                   script-binding stats/display-stats
Q                   quit-watch-later
J                   cycle sub down; show-text "Subtitle: ${sub}"
Alt+J               cycle secondary-sid down; show-text "Secondary sub: ${secondary-sid}"
Ctrl+v              loadfile ${clipboard/text} append-play; show-text '+ ${clipboard/text}'
Ctrl+w              quit
Ctrl+KP_Subtract    add video-zoom -0.05; show-text "Zoom: ${video-zoom}"
Ctrl+KP_Add         add video-zoom +0.05; show-text "Zoom: ${video-zoom}"
Ctrl+KP1            add video-pan-x -0.01; add video-pan-y +0.01; show-text "Horizontal offset: ${video-pan-x}, Vertical offset: ${video-pan-y}"
Ctrl+KP3            add video-pan-x +0.01; add video-pan-y +0.01; show-text "Horizontal offset: ${video-pan-x}, Vertical offset: ${video-pan-y}"
Ctrl+KP7            add video-pan-x -0.01; add video-pan-y -0.01; show-text "Horizontal offset: ${video-pan-x}, Vertical offset: ${video-pan-y}"
Ctrl+KP9            add video-pan-x +0.01; add video-pan-y -0.01; show-text "Horizontal offset: ${video-pan-x}, Vertical offset: ${video-pan-y}"
Ctrl+KP_Pgup        add video-align-x +0.01; add video-align-y -0.01; show-text "Horizontal align: ${video-align-x}, Vertical align: ${video-align-y}"
Ctrl+KP_Home        add video-align-x -0.01; add video-align-y -0.01; show-text "Horizontal align: ${video-align-x}, Vertical align: ${video-align-y}"
Ctrl+KP_Pgdwn       add video-align-x +0.01; add video-align-y +0.01; show-text "Horizontal align: ${video-align-x}, Vertical align: ${video-align-y}"
Ctrl+KP_End         add video-align-x -0.01; add video-align-y +0.01; show-text "Horizontal align: ${video-align-x}, Vertical align: ${video-align-y}"
Ctrl+KP5            set video-pan-x 0; set video-pan-y 0; show-text "Reset offset"
Ctrl+KP_Begin       set video-align-x 0; set video-align-y 0; show-text "Reset alignment"
Ctrl+Alt+KP5        set video-scale-x 1; set video-scale-y 1; show-text "Reset vertical/horizontal scale"
