## Whether to escape menu titles. Default yes
escape_title=yes
## Maximum menu title length. Default 80; longer titles are truncated
## Set to 0 for no limit
max_title_length=40
## Maximum number of playlist menu items. Default 20
## Set to 0 to disable playlist menu
max_playlist_items=20

uosc_syntax=yes
