# Enable script. Default yes
#! Can be changed at runtime
enabled=yes
# Path for recent playback list (recentmenu). Relative or absolute, mpv path rules
path=~~/cache/recent.json
# Max number of recent entries. Default 10
length=20
# Only keep the latest entry per same-series in same directory. Default yes
# When enabled, only the last played file in a series (by similarity) is stored; may misidentify
ignore_same_series=yes